# ~/.config/starship.toml




#add_newline = false

#[line_break]
#disable = true
# Use custom format
format = """
[┌───────────────────|](bold green)
[│](bold green)  $directory(bold green)
[└─>](bold green) """

#[rlang]
#format = "- [R $version](blue bold) "

#[directory]
#read_only = " "

#[git_branch]
#symbol = " "
